version: '3.8'

services:
  customer-person:
    build:
      context: .
      dockerfile: api-msa-bpt-customer-person/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENV_MICROSERVICE_FLYWAY_DATASOURCE=jdbc:postgresql://db:5432/test_db
      - ENV_MICROSERVICE_JPA_DATASOURCE=jdbc:postgresql://db:5432/test_db
      - ENV_MICROSERVICE_DATASOURCE=r2dbc:postgresql://db:5432/test_db
      - ENV_MICROSERVICE_DATASOURCE_USERNAME=postgres
      - ENV_MICROSERVICE_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  account-movements:
    build:
      context: .
      dockerfile: api-msa-bpt-account-movements/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ENV_MICROSERVICE_FLYWAY_DATASOURCE=jdbc:postgresql://db:5432/test_db
      - ENV_MICROSERVICE_JPA_DATASOURCE=jdbc:postgresql://db:5432/test_db
      - ENV_MICROSERVICE_DATASOURCE=r2dbc:postgresql://db:5432/test_db
      - ENV_MICROSERVICE_DATASOURCE_USERNAME=postgres
      - ENV_MICROSERVICE_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: